Update chair_cheat_sheet.md
decentralized-identity/org pull request #28
Opened 2024-02-14 00:25 UTC by kimdhamilton

Small fixes and updates to generalize for all group types

- Edits for typos and brevity
- Slight reorganization and edits to clarify which are relevant to Open Groups vs Working Groups

There are some items I'm not completely sure about w.r.t Open Groups vs Working Groups, so I can follow up with a subsequent PR, e.g. "If a DIF wg chair steps down, the WG can nominate new chairs. The preferred method for electing the new chair is via consensus. If there is no consensus within the group then voting must be organized - rules for the voting process are in DIF's charter. "

Also, this link https://identity.foundation/#wgs isn't valid; it should be https://identity.foundation/working-groups/. At the same time, that's currently going to the Events page. I'll create a separate issue there

2024-03-25 17:09 UTC, andorsk requested changes
Move out the passcode for Zoom into someplace more privacy sensitive.

2024-03-25 17:09 UTC, andorsk commented on chair_cheat_sheet.md
> +    - 212121
This is good, but this repo is public. Can we move this to a secret manager somewhere else or DM people?

2024-03-30 03:08 UTC, kimdhamilton commented on chair_cheat_sheet.md
> +    - 212121
good point; we have this in the other chair instructions too. We can move it out

2024-04-05 22:39 UTC, kimdhamilton commented on chair_cheat_sheet.md
> +    - 212121
Note that this code is already in the instructions above; it was just moved here. Perhaps create a separate issue to track that?

2024-04-08 13:21 UTC, andorsk requested changes

2024-04-16 12:46 UTC, ankurdotb approved these changes

2024-04-20 01:31 UTC, merged