Create create_group.md
decentralized-identity/org pull request #34
Opened 2024-03-23 19:48 UTC by kimdhamilton

Add proposed steps for creating a DIF group. This is reverse engineered from observation and current practices. Input is welcome

2024-03-25 17:13 UTC, andorsk requested changes
minor spacing issues.

2024-03-25 17:13 UTC, andorsk commented on Org documents/processes/create_group.md
> +
```suggestion
```

2024-03-25 17:13 UTC, andorsk commented on Org documents/processes/create_group.md
> +- Link to approved charter
The template should have <FILL-ME> sections or something with instructions.

2024-04-05 22:37 UTC, kimdhamilton commented on Org documents/processes/create_group.md
> +- Link to approved charter
I think I see the disconnect. Yes, they should have instructions. Our struggle, and why I'm submitting this PR, is that DIF has no such instructions, for pretty much anything process-wise. This is about baby-stepping our way to instructions, which TSC and DIF core team can co-create (I believe no single person possesses the institutional knowledge to perform this)

I also clarified that the target audience of this is DIF core team and TSC. Currently, we cobble this together over slack (as I've discovered when launching the groups since I've joined). So this is about documenting these steps for our own knowledge, and for transparency to the broader community.

2024-04-08 13:20 UTC, andorsk approved these changes

2024-04-08 15:04 UTC, merged