reformat + acks section
decentralized-identity/org pull request #9
Opened 2022-01-10 22:20 UTC by bumblefudge

- adds acknowledgements policy discussed at [July Technical Steering Committee meeting](https://github.com/decentralized-identity/TSC/blob/main/agenda.md#meeting---7-july-2021---1300-et) 
- cleans up line-breaks and a few minor editorial nits

2022-01-11 08:59 UTC, peacekeeper approved these changes

2022-01-12 17:44 UTC, OR13 requested changes
> If the WG decides by consensus not to include an acknowledgments section, this decision should be recorded in the minutes/issues for the sake of transparency.

I don't believe this should be allowed... especially with no formal definition of `consensus`.

2022-01-12 17:45 UTC, OR13 commented on work-item-lifecycle.md
> +2. The WG approval process SHOULD consider adding a "Acknowledgments" section to
```suggestion
2. The WG approval process MUST consider adding a "Acknowledgments" section to
```

2022-01-12 17:45 UTC, OR13 commented on work-item-lifecycle.md
> +   or institutional support such as research grants or university labs. If the
```suggestion
   or institutional support such as research grants or university labs. 
```

2022-01-12 17:45 UTC, OR13 commented on work-item-lifecycle.md
> +   WG decides by consensus not to include an acknowledgments section, this
```suggestion
   
```

2022-01-12 17:45 UTC, OR13 commented on work-item-lifecycle.md
> +   decision should be recorded in the minutes/issues for the sake of
```suggestion
   
```

2022-01-12 17:45 UTC, OR13 commented on work-item-lifecycle.md
> +   transparency.
```suggestion
 
```

2022-01-12 17:46 UTC, OR13 requested changes
Specifically, working groups MUST NOT be allowed to obstruct acknowledgements from contributors, when requested.

2022-01-12 17:50 UTC, OR13 commented
Related PR which should be merged before this PR is:

https://github.com/decentralized-identity/sidetree/pull/1133

2022-01-12 18:09 UTC, OR13 commented
This PR is now blocked by the requested changes here: https://github.com/decentralized-identity/sidetree/pull/1133#discussion_r783318836

2022-01-13 20:28 UTC, OR13 commented
@csuwildcat you requested the following structure for acknowledgements here: https://github.com/decentralized-identity/sidetree/pull/1133#discussion_r783318836

> I would suggest changing the language to: "ENTITY_NAME_HERE received funding from the United States Department of Homeland Security's (US DHS) Silicon Valley Innovation Program to contribute to this work item under contracts 70RSAT20T00000003, and 70RSAT20T00000033. This work item does not necessarily reflect the position or the policy of the U.S. Government and no official endorsement should be inferred."

I would request that request this format of all work item acknowledgement section on this pull request.

We will assume you will be successful, and update our PR accordingly, but this PR should not be merged until proper guidance is given.

2022-01-26 20:01 UTC, bumblefudge commented on work-item-lifecycle.md
> +2. The WG approval process SHOULD consider adding a "Acknowledgments" section to
Ran this by the TSC at today's meeting, there was not support for this being mandatory. if no one PRs in any acknowledgements, should there be an empty section?

2022-01-26 20:06 UTC, bumblefudge commented on work-item-lifecycle.md
> +2. The WG approval process SHOULD consider adding a "Acknowledgments" section to
Maybe a better wording than "MUST consider" is "MUST make a last call for acknowledgement PRs" to make it clear that WG members are responsible to PR in their acknowledgments before or as part of final editorial pass.

2022-01-27 20:57 UTC, bumblefudge commented
Hey @OR13 , updated the PR a bit and discussed at yesterday's TSC.  I think TSC, not SC, has the final say on `work-item-lifecycle.md` and hopefully the addition of a template makes future cases more cut-and-dry.  Apologies for all the delay. Can I ask you to re-review?

2022-03-23 17:37 UTC, merged